name: Tara Parker-Essig
favicon: null
layout_spectrum: 1
typography_spectrum: 0.77649
title: Tara Blogs Casually About Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#613c58'
    - '#838689'
    - '#e8e6a4'
    - '#c5daaf'
    - '#a2cdb9'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
