name: Tara
favicon: null
layout_spectrum: 0.5293603164609522
typography_spectrum: 0.5607076520100236
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5569563382305205
  lightness: 0.8870458812452853
  saturation: 0.46971277240663767
  rhythmicContrast: 0.1388489392120391
purpose: []
