name: Casually About Design
favicon: null
layout_spectrum: 0.74952
typography_spectrum: 0.77649
title: Tara Blogs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f5f5'
    - '#568ec9'
    - '#000000'
    - '#3d355f'
    - '#97ba00'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 0
purpose: []
